fix cicd bug

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -5,20 +5,20 @@ jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+      - run: echo "🎉 Welcome to Our project "
+      - run: echo "🐧 This project is About the COMP90024"
+      - run: echo "🔎 The Teammate of my team are GaoYuan Ou. Jonghao Ou. Shiya Fu. Mingyi Li. Zhuoyang Liu"
       - name: Check out repository code
         uses: actions/checkout@v4
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
       - name: Run test_aip.sh
         run: |
-          ../test/test_aip.sh || echo "test_aip.sh failed" >> failed_logs.txt
+          cd ./test
+          ./test_aip.sh || echo "test_aip.sh failed" >> failed_logs.txt
       - name: Run UT.sh
         run: |
-          ../test/UT.sh || echo "UT.sh failed" >> failed_logs.txt
+          cd ./test
+          ./UT.sh || echo "UT.sh failed" >> failed_logs.txt
